- README.rst
- giddy/__init__.py
- giddy/markov.py
- giddy/tests/test_markov.py
> passing markov tests after reorg

- giddy/components.py
- setup.py
* adjust print statement in component.py
* version bump to 1.0.2: `pip install giddy` should be working fine in python 3x
> adjust print statement and version bump

- .travis.yml
- giddy/components.py
- giddy/directional.py
- giddy/inequality/__init__.py
- giddy/inequality/_indices.py
- giddy/inequality/gini.py
- giddy/inequality/tests/test_gini.py
- giddy/inequality/tests/test_theil.py
- giddy/inequality/theil.py
- giddy/markov.py
- giddy/rank.py
- giddy/tests/test_directional.py
- giddy/tests/test_util.py
- setup.py
this prepares giddy to drive inequality & distribution dynamics code in the final pysal metapackage. 
specifically it
1. adds the `inequality` module to giddy in hopes of extensions to space-time
2. casts the library to a common subset of py2/py3 compatible code, so tests will run without 2to3 conversion. 
3. changes the travis file to accommodate these changes.
> [WIP] prepare for full metapackage integration

- .travis.yml
- giddy/api.py
- giddy/components.py
- giddy/directional.py
- giddy/inequality/__init__.py
- giddy/inequality/_indices.py
- giddy/inequality/gini.py
- giddy/inequality/tests/test_gini.py
- giddy/inequality/tests/test_theil.py
- giddy/inequality/theil.py
- giddy/markov.py
- giddy/mobility.py
- giddy/rank.py
- giddy/tests/test_api.py
- giddy/tests/test_directional.py
- giddy/tests/test_util.py
- setup.py
Addressing #26 
Need to add inequality to api after #25 is merged.
> api module for giddy

- README.rst
- giddy/__init__.py
- giddy/version.py
- setup.py
- tools/github_stats.py
- Add `__version__` attirbute
- Borrow code from pysal to generate changelog
> prepare for release

- .travis.yml
- giddy/directional.py
- giddy/tests/test_directional.py
test and documentation for `rose.plot()` and `rose.plot_vectors()`
added tests
added documentation
added DeprecationWarning 
added `splot` install to `.travis.yml`
> Tests and documentation for `rose.plot()` and `rose.plot_vectors()`

- MANIFEST.in
- doc/conf.py
- giddy/directional.py
- requirements_tests.txt
- setup.py
* Configure setup to include /tests in the next release (respond to https://github.com/pysal/pysal/issues/1046)
* Correct doctests in directional.py
> include /tests in the release and correct for the directional doctests

- .travis.yml
- testing/matplotlibrc
This is to mimic the dual travis testing for spreg https://github.com/pysal/spreg/pull/9 to test aganist API changes of libpysal.
> set up dual travis tests for libpysal (pip and github)

- giddy/__init__.py
- giddy/version.py
- setup.py
Conform with the versioning fashion in `libpysal` and `pysal/submodule_template`
> version giddy only in giddy/__ini__.py

- .travis.yml
> explicitly specifying Miniconda3 in .travis.yml

- .travis.yml
Following the metapackage pysal/pysal https://github.com/pysal/pysal/pull/1095
> Move testing off of 3.5 and add 3.7

- .travis.yml
follow https://github.com/pysal/splot/pull/69
> pip install github master.zip of pysal dependencies

- README.md
- README.rst
- setup.py
Go back to README.md for pypi project description as [README.rst is not rendered properly](https://pypi.org/project/giddy/)
> PyPi page configuration

- doc/_static/references.bib
- doc/api.rst
- doc/generated/giddy.sequence.Sequence.rst
- giddy/__init__.py
- giddy/sequence.py
- giddy/tests/test_sequence.py
- notebooks/Sequence.ipynb
- requirements_tests.txt
This PR is to add alignment-based sequence methods to giddy. Six options for setting the operation costs are available: 
* "hamming": hamming distance (substitution only and its cost is constant 1) from sklearn.metrics;
* "markov": utilize empirical transition probabilities to define substitution costs;
* "interval": differences between states are used to define substitution costs and indel=k-1;
* "arbitrary": arbitrary distance if there is not a strong theory guidance: substitution=0.5, indel=1.
* "tran": transition-oriented optimal matching. 
* user-defined cost operations
> (ENH) Sequence methods

- README.md
- README.rst
update Readme for v2.2.0:
* zenodo badge
* pypi badge
> update Readme for v2.2.0

- README.md
- giddy/__init__.py
* version bump
* add example notebooks to readme
> Prepare for new release 2.2.1 which will have the addition of sequence methods

- CHANGELOG.md
- README.md
- README.rst
- doc/index.rst
- tools/gitcount.ipynb
update docs for release v2.2.1
> docs updates for v2.2.1

- doc/conf.py
- doc/notebooks/MarkovBasedMethods.ipynb
- doc/notebooks/MobilityMeasures.ipynb
- doc/notebooks/RankMarkov.ipynb
- doc/notebooks/RankbasedMethods.ipynb
- doc/notebooks/directional.ipynb
- doc/tutorial.rst
* fix docs building https://github.com/pysal/giddy/issues/114 
* configure nbsphinx to work with binder in docs tutorials
> (docs, bug) fix docs building and configure nbsphinx to work with binder in docs tutorials

- README.md
- README.rst
> resolving broken dev link

- giddy/rank.py
- giddy/tests/test_rank.py
> BUG: Fix for correct handling of ties in Tau

- CHANGELOG.md
- giddy/__init__.py
- tools/gitcount.ipynb
* bump version 
* changelog
address https://github.com/pysal/giddy/issues/121
> prepare for new release: version 2.2.2 

- giddy/util.py
This PR is to rewrite the utility function `get_lower` to use numpy's more efficient functionalities.
> rewrite utility function "get_lower" using numpy's more efficient functionality

- .travis.yml
this PR is to allow for testing against submodules' github master branch in .travis.yml https://github.com/pysal/pysal/issues/1145
> travis CI: pip install from git clone

- doc/conf.py
This PR provides a fix for the broken link issue raised in #129
> fix for #129

- giddy/markov.py
- giddy/mobility.py
correct grammar for summary output for Markov chains
address https://github.com/pysal/giddy/issues/133
> rewording summary output for Markov chains

- .github/workflows/release_and_publish.yml
Configure a workflow with github actions for streamlining package building, release, and publishing.
Benefitting from geosnap's workflow https://github.com/spatialucr/geosnap/pull/221 and spaghetti's workflow https://github.com/pysal/spaghetti/pull/489
> release and publish with github actions

- .github/workflows/release_and_publish.yml
- tools/gitcount.ipynb
* syntax fix for the workflow of GitHub actions for building and releasing a package
* update tools/gitcount.ipynb
* borrow from `geosnap` for automatically obtaining starting and releasing dates
* insert the content of the new changes at the beginning of [CHANGELOG.md](https://github.com/pysal/giddy/blob/master/CHANGELOG.md)
> (bug) fix workflow of GitHub actions for building and releasing a package

- .github/workflows/unittests.yml
Give a name to the continuous testing workflow and fix indentation
> Give a name to the continuous testing workflow

- .github/workflows/release_and_publish.yml
fix workflow of building and releasing:
* add testing pypi site
> (bug) fix workflow of building and releasing 

- .github/workflows/release_and_publish.yml
- giddy/__init__.py
adjust the order of the packing and releasing steps of github actions workflow so that the updated changelog can be incorporated in the built distribution
> GitHub actions (packing and releasing) - pack the updated changelog to the built distribution

- .github/workflows/unittests.yml
`esda` default branch in now `main`.
> default esda branch master -> main

- .github/workflows/release_and_publish.yml
- setup.py
The current github action for package release is not working. Update the .yml file that follows the [one from the spaghetti package](https://github.com/pysal/spaghetti/blob/main/.github/workflows/release_and_publish.yml).
> update github action for release

- giddy/markov.py
- giddy/sequence.py
fix https://github.com/pysal/giddy/issues/190
> fix ValueError: setting an array element with a sequence

- docs/conf.py
- giddy/ergodic.py
- giddy/markov.py
- giddy/rank.py
- giddy/sequence.py
- requirements_docs.txt
- tools/gitcount.ipynb
***Only formatting. No changes in functionality***
This PR formats the repo with [`black`](https://black.readthedocs.io/en/stable/). It is a prerequisite to get started on #200. Once this PR is reviewed and merged, I will lint the repo with [`ruff`](https://github.com/astral-sh/ruff).
> black format repo

- environment.yml
this is an attempt to fix environment.yml https://github.com/pysal/giddy/issues/209
> (bug) fix environment.yml

- .github/workflows/tests.yml
This PR:
* resolves #223 
* xref https://github.com/pysal/pysal/issues/1298
> test against macOS intel chip
